Repository CupStation/DesertCup, pull requests merged in 2020-07, with the labels that each got.

#13 Delete startFO13.sh - Testing other stuff
  startFO13.sh
Labels: Removal

#16 Removes castration surgery
  code/modules/surgery/gender_reassignment.dm
Labels: Removal

#17 Extremely minor super-stimpak edit
  code/modules/reagents/chemistry/reagents/medicine_reagents.dm
Labels: Tweak

#18 Certain wasteland drugs are now mixable
  code/modules/reagents/chemistry/recipes/drugs.dm
Labels: Feature

#19 Adds a new 'Ultra Stimpak'
  code/modules/reagents/chemistry/reagents/medicine_reagents.dm
  code/modules/reagents/reagent_containers/hypospray.dm
Labels: Feature

#20 Vaults no longer get OP medical gear roundstart
  code/game/objects/effects/spawners/f13lootdrop.dm
Labels: Balance/Rebalance

#23 Remove ERP code from Legion namecheck
  code/modules/jobs/job_types/legion.dm
Labels: Removal

#24 Experimental Stimpaks are no longer a death sentence
  code/modules/reagents/chemistry/reagents/medicine_reagents.dm
Labels: Fix
